name: Release Firmware

on:
  release:
    types: [created]

jobs:
  build:
    uses: ./.github/workflows/build.yml

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download firmware artifact
        uses: actions/download-artifact@v4
        with:
          name: firmware

      - name: Rename firmware binary for release
        run: mv firmware.elf.bin firmware.bin

      - name: Upload firmware to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: firmware.bin

      - uses: shallwefootball/s3-upload-action@master
        name: Upload S3
        id: S3
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: 'firmware.bin'
          destination_dir: firmware-${{ github.event.release.tag_name }}.bin
