name: Release Firmware

on:
  release:
    types: [created]

jobs:
  build:
    uses: ./.github/workflows/build.yml

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download firmware artifact
        uses: actions/download-artifact@v4
        with:
          name: firmware

      - name: Rename firmware binary for release
        run: mv firmware-*.bin firmware-${{ github.event.release.tag_name }}.bin

      - name: Upload firmware to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: firmware-${{ github.event.release.tag_name }}.bin
